source_list:
  - SB
  - OL
  - CP
  - ADDR

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

CP:
  s3_conf:
    s3_bucket: sureshboddu

ADDR:
  mongodb_config:
    database: customer
    collection: address


s3_conf:
  s3_bucket: sureshboddu
  staging_dir: pg_staging


REGIS_DIM:
  tableName:"DATAMART.REGIS_DIM"
  sourceData:
    - CP
    - ADDR
  loadingQuery: SELECT