source_list:
  - SB
  - OL
  - CP
  - ADDR

target_list:
  - REGIS_DIM
  #- CHILD_DIM
  #- RTL_TXN_FCT

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

CP:
  s3_conf:
    s3_bucket: sureshboddu

ADDR:
  mongodb_config:
    database: customer
    collection: address


s3_conf:
  s3_bucket: sureshboddu
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT * from DATAMART.REGIS_DIM

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  sourceData:
    - CP
    - ADDR
  loadingQuery: >
    SELECT
      FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,CAST(REGIS_CTY_CODE AS SMALLINT) AS CTY_CODE,
      CAST(REGIS_ID AS INTEGER) as REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_DT,
      city, state, street, addr_ins_dt
    FROM
     (SELECT
       DISTINCT a.REGIS_CNSM_ID, CAST(a.REGIS_CTY_CODE AS SMALLINT), CAST(a.REGIS_ID AS INTEGER),
       a.REGIS_LTY_ID, a.REGIS_DATE, a.REGIS_CHANNEL, a.REGIS_GENDER, a.REGIS_CITY, a.INS_DT,
       b.city, b.state, b.street, b.ins_dt as addr_ins_dt
      FROM
        CP a join ADDR b
      ON a.REGIS_CNSM_ID = b.consumer_id
      WHERE
        a.INS_DT = '2020-11-01'
     ) CP

CHILD_DIM:
  tableName: DATAMART.CHILD_DIM
  sourceData:
    - CP
  loadingQuery: >
    SELECT
    FN_UUID() CHILD_KEY, REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM
    (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, INS_DT
    FROM
    CP
    WHERE
      INS_DT = '2020-11-02'
    ) CP


RTL_TXN_FCT:
  sourceData:
    - SB
    - OL
  sourceTable:
    - DATAMART.REGIS_DIM
  tableName: DATAMART.RTL_TXN_FCT
  loadingQuery: >
    SELECT
    	FN_UUID() AS RTL_TXN_KEY, CAST(TXN.APP_TRANSACTION_ID AS STRING)AS TXN_ID, SIZE(split(REC.PRODUCTS, ',')) AS TXN_ITEM_QTY,
    	TRANSACTION_POINT_VALUE AS TXN_LOY_VAL_STD_CCY, 0 AS TXN_GROSS_MNY_STD_CCY, TRANSACTION_RETAIL_VALUE AS TXN_GROSS_MNY_LCL_CCY,
    	-1 AS MNY_LCL_CCY_TYPE_KEY, TRANSACTION_EXTERNAL_REFERENCE AS RTL_TXN_TYPE_KEY, ACTIVITY_TIMESTAMP AS TXN_TS,
    	CAST(ACTIVITY_TIMESTAMP AS DATE) AS TXN_DT_KEY, HOUR(ACTIVITY_TIMESTAMP) AS TXN_TM_HOUR, MINUTE(ACTIVITY_TIMESTAMP) AS TXN_TM_MINUTE,
    	SECOND(ACTIVITY_TIMESTAMP) AS TXN_TM_SECOND, '-1' AS CHNL_KEY, REG.CNSM_ID AS CNSM_ID,
    	"@NULL@" AS RTL_TXN_EXT_DEC_1, "@NULL@" AS RTL_TXN_EXT_DEC_2, REC.BASE_POINT_VALUE AS
    	RTL_TXN_EXT_DEC_3, MOBILE_UID AS RTL_TXN_EXT_CHAR_1, MOBILE_OS AS RTL_TXN_EXT_CHAR_2, PRODUCTS AS RTL_TXN_EXT_CHAR_3,
    	RECEIPT_STATUS AS RTL_TXN_EXT_CHAR_4, CAST(MSG_CODE AS BIGINT) AS RTL_TXN_EXT_CHAR_5, TXN.INS_DT AS INS_TS
    FROM
    	SB TXN LEFT OUTER JOIN OL REC
    	ON (TXN.APP_TRANSACTION_ID = REC.SBLP_TRANSACTION_ID )
    	LEFT OUTER JOIN DATAMART.REGIS_DIM REG
    	ON TXN.LOYALTY_ID = REG.CNSM_ID
    WHERE
    	 TXN.INS_DT = '2020-11-02'
    			AND (REC.INS_DT = '2020-11-02' OR REC.INS_DT is NULL)